"""create users table

Revision ID: 804666f082b4
Revises: 0a305c276259
Create Date: 2025-08-02 01:37:14.796274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '804666f082b4'
down_revision: Union[str, Sequence[str], None] = '0a305c276259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_category_relationships_ancestor_descendant'), table_name='category_relationships')
    op.drop_table('category_relationships')
    op.drop_table('category_brand_association')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_table('brands')
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_table('brands',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('brands_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='brands_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_table('category_brand_association',
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('category_brand_association_brand_id_fkey')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('category_brand_association_category_id_fkey'))
    )
    op.create_table('category_relationships',
    sa.Column('ancestor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descendant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('depth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ancestor_id'], ['categories.id'], name=op.f('category_relationships_ancestor_id_fkey')),
    sa.ForeignKeyConstraint(['descendant_id'], ['categories.id'], name=op.f('category_relationships_descendant_id_fkey')),
    sa.PrimaryKeyConstraint('ancestor_id', 'descendant_id', name=op.f('category_relationships_pkey'))
    )
    op.create_index(op.f('ix_category_relationships_ancestor_descendant'), 'category_relationships', ['ancestor_id', 'descendant_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('selling_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('products_brand_id_fkey')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('products_category_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###
