"""add selling_price and discount_price to products table

Revision ID: f93a122aa3ca
Revises: 455c415f1071
Create Date: 2025-07-30 02:07:50.494845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93a122aa3ca'
down_revision: Union[str, Sequence[str], None] = '455c415f1071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None






def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('selling_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('discount_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount_price')
    op.drop_column('products', 'selling_price')
    # ### end Alembic commands ###